# Define the tesseract language
#
language: deu

# Where the receipts are stored
# Receipts should be simple text files
receipts_path: "data/txt"

results_as_json: false

# Market names roughly ordered by likelihood.
# Can contain market locations for fuzzy parsing
markets:
  BOOK TA .K (TAMAN DAYA) SDN BHD:
    - book ta -k (taman daya) sdn bhd
    - BOOK TA .K (TAMAN DAYA) SDN BHD
  INDAH GIFT & HOME DECO:
    - INDAH GIFT & HOME DECO
    - indah gift & home deco
  Colruyt:
     - colruyt
     - Colruyt
  Delhaize:
     - Delhaize
     - delhaize
  Penny:
     - penny markt
     - penny
     - p e n n y
     - m a r k t gmbh
  REWE:
     - rewe
  Real:
     - real
  Netto:
     - netto-online
  Kaiser's:
     - kaiser
     - kaiserswerther straße 270
  Aldi:
     - aldi
     - friedrichstr 128—133
  Lidl:
     - lidl
  Edeka:
    - edeka
  Drogerie:
     - drogerie
  Kodi:
     - kodi
  Getraenke:
    - Getraenke Tempel
  Tanken:
     - shell
     - esso station
     - aral
     - total tankstelle
     - RK Tankstellen
  Migros:
     - genossenschaft migros
  Metro:
     - vetro
     - metro

  MR D.I.Y. SDN BHD:
    - MR D.I.Y. (JOHOR) SDN BHD
    - MR D.I.Y. (M) SDN BHD
    - MR. D.I.Y. (M) SDN BHD
    - MR.D.I.Y(M)SDN BHD
    - MR. D.I.Y. SDN BHD
    - MR. D.I.Y. (KUCHAI) SDN BHD
    - MR. D. I. Y. (KUCHAI) SDN BHD
    - MR. D. I. Y. (M) SDN BHD

  YONGFATT ENTERPRISE:
    - YONGFATT ENTERPRISE

#  ABC HO TRADING
#  SOON HUAT MACHINERY ENTERPRISE
#  S.H.H. MOTOR (SUNGAI RENGIT) SDN. BHD.
#  PERNIAGAAN ZHENG HUI
#  GERBANG ALAF RESTAURANTS SDN BHD
#  SAM SAM TRADING CO
#  AIK HUAT HARDWARE ENTERPRISE (SETIA ALAM) SDN BHD
#  HOME MASTER HARDWARE & ELECTRICAL
#  RESTORAN HASSANBISTRO
#  ASIA MART
#  LIGHTROOM GALLERY SDN BHD
#  SHELL ISNI PETRO TRADING
#  SYL ROASTED DELIGHTS SDN. BHD.
#  TEO HENG STATIONERY & BOOKS
#  FUYI MINI MARKET
#  TED HENG STATIONERY & BOOKS
#  99 SPEED MART S/B
#  C W KHOO HARDWARE SDN BHD
#  UNIHAKKA INTERNATIONAL SDN BHD
#  AEON CO. (M) BHD
#  WARAKUYA PERMAS CITY SDN BHD
#  YHM AEON TEBRAU CITY
#  OWNER BY CASTLE BLUE S/B
#  THREE STOOGES
#  TASTE OF THE WORLD SDN BHD
#  32 PUB & BISTRO OWN BY CNU TRADING
#  PASAR MINI JIN SENG
#  RESTAURANT SIN DU
#  YONG TAT HARDWARE TRADING
#  TIMELESS KITCHENETTE SDN BHD
#  PAGOH REST AND SERVICE AREA
#  CARREFOUR RESTAURANT
#  TRIPLE SIX POINT ENTERPRISE 666
#  BENS INDEPENDENT GROCER SDN. BHD
#  NANDO'S CHICKENLAND MALAYSIA SDN BHD
#  PETRODELI ENTERPRISE
#  SUN WONG KUT SDN BHD
#  RESTAURANT JIAWEI JIAWEI HOUSE
#  PASARAYA BORONG PINTAR SDN BHD
#  LIAN CHI PU TIAN VEGETARIAN RESTAURANT SDN BHD
#  POPULAR BOOK CO. (M) SDN BHD
#  LIAN HING STATIONERY SDN BHD
#  GL HANDICRAFT & TAIL ORING
#  BANH MI CAFE SDN BHD
#  THAI DELICIOUS RESTAURANT
#  HON HWA HARDWARE TRADING
#  VIVOPAC MARKETING SDN BHD
#  IKANO HANDEL SDN BHD
#  FY EAGLE ENTERPRISE
#  TRI SHAAS SDN BHD
#  ADVANCO COMPANY
#  AEON CO. (M) BHD.
#  WAHIN HARDWARE SDN BHD
#  SYARIKAT PERNIAGAAN GIN KEE
#  T.A.S LEISURE SDN BHD
#  SWEET FOREST CAFE
#  BEYOND BROTHERS HARDWARE
#  ZAWIAJAYA FOOD N BEVERAGE SDN BHD
#  LIM SENG THO HARDWARE TRADING
#  SUN VICTORY SDN BHD
#  RESTORAN IBRAHIM MAJU SB
#  FARMASI MALURI S/B
#  ASO ELECTRICAL TRADING SDN BHD
#  RESTORAN WAN SHENG
#  RSTORAN WAN SHENG
#  PAPPARICH BMC
#  MIZU MENTAI SDN. BHD.
#  HAPPY SNACKS ENTERPRISE
#  SWC ENTERPRISE SDN BHD
#  L TWO FLORIST & HANDICRAFT
#  WATSON'S PERSONAL CARE STORES SDN BHD
#  KHE ELECTRICAL TRADING
#  TK DIVISION KITCHEN SDN BHD
#  GOLDEN SCOOP SDN BHD
#  FUN N CHEER (MALURI)
#  CT281 - TEALIVE SHELL KEPONG OTTOGO ENTERPRISE
#  NADEJE PRESTIGE SDN BHD
#  SUNFISH
#  MR . DAKGALBI SOLARIS
#  THE STORE (MALAYSIA) SDN BHD
#  LITTLE CRAVINGS SDN BHD
#  KING'S CONFECTIONERY S/B
#  YAM FRESH
#  ZEN AND COFFEE 28 S/B
#  GUARDIAN HEALTH AND BEAUTY SDN BHD
#  DOMMAL FOOD SERVICES SDN BHD
#  MY HAPPY PHARMACY PLT
#  KEDAI PAPAN YEW CHUAN
#  BHPETROL SUBANG AIRPORT
#  BHPETROL PALEKBANG
#  BILLION SIX ENTERPRISE
#  SLF CASH & CARRY
#  SUPER SEVEN CASH & CARRY SDN BHD
#  URBAN IDEA SDN BHD
#  KMF FOODICIOUS SDN BHD
#  YONG CEN ENTERPRISE
#  ENW HARDWARE CENTRE (M) SDN BHD
#  TSH POWER HARDWARE TRADING
#  BAIFU (M) SDN BHD
#  GOLDEN KEY MAKER
#  ELITETRAX MARKETING SDN BHD
#  KAISON FURNISHING SDN BHD
#  LEE WAH FLORIST SDN BHD
#  SINNATHAMBY HOLDINGS SDN. BHD.
#  TRENDYMAX (M) SDN. BHD.
#  PRINT EXPERT SDN BHD
#  BOON SENG PAPER SDN BHD
#  RELAIS TOTAL OULMES
#  TONYMOLY VIVA CITY
#  ANZEL ADVERTISING (M) SDN BHD
#  PREMIO STATIONERY SDN BHD
#  Y SOON FATT S/B
#  BEMED (SP) SDN BHD
#  B & BEST RESTAURANT
#  OLIVE9 PHARMACY SDN BHD
#  SEGI CASH & CARRY SDN. BHD.
#  TANJONGMAS BOOKCENTRE (PJ) SDN BHD
#  BEMED (SP) SDN. BHD.
#  SEGI CASH & CARRY SDN.BHD
#  GOLDEN ARCHES RESTAURANTS SDN BHD
#  MEI LET RESTAURANT
#  YONG SOON FATT S/B
#  AMPANG 210 FIRST CITY PARKING SDN BHD
#  GL HANDICRAFT & TAII ORING
#  ARTRANGE STATIONERS & PRINT SDN BHD
#  TIMES BOOKSTORES
#  TOKYO KITCHEN (CITTA MALL) TOKYO KITCHEN SDN BHD
#  AMANO MALAYSIA SDN BHD
#  PERNIAGAAN RIANG RIA
#  HERO DISTRIBUTION SDN BHD
#  BROADVIEW MARKETING SDN BHD
#  IN-SPARKLE TRADING SDN BHD
#  ELKEN SERVICE SDN BHD
#  FIVE STAR CASH & CARRY
#  SUPER.SEVEN CASH & CARRY SDN BHD
#  S&Y STATIONERY
#  DI HUAN YA RESTAURANT
#  RESTORAN SIAM VILLAGE
#  HASHA PETROKIOSK
#  BHPETROL PERMAS JAYA 2
#  LAVENDER CONFECTIONERY & BAKERY S/B
#  SELASIH EKSLUSIF SDN BHD
#  DOMINO'S PIZZA
#  THE COFFEE BEAN & TEA LEAF (M) SDN. BHD.
#  DE MAXIMUM THAI EXPRESS SDN BHD
#  AEON CO. (M) SDN BHD
#  THE TOAST F&B SDN BHD
#  PASARAYA JALAL SDN BHD
#  TF VALUE-MART SDN BHD
#  CHECKERS HYPERMARKET SDN BHD (JALAN KLANG LAMA)
#  BERRY'S CAKE HOUSE
#  WESTERN EASTERN STATIONERY SDN. BHD
#  WESTERN EASTERN ST TIONERY SDN. BHD
#  GHEE HIANG GH DISTRIBUTOR & MARKETING SDN BHD
#  MENTAI INITIAL SDN BHD
#  THE ROTI MAN BAKERY
#  HAXINCONE RESOURCES SDN BHD
#  FAMILYMART
#  R&C VENTURE SDN BHD
#  SUBANG HEALTHCARE SDN BHD
#  DIGI TELECOMMUNICATIONS SDN BHD
#  KHIAM AIK CHAN SDN BHD
#  GARDENIA BAKERIES (KI ) SDN BHD
#  GARDENIA BAKERIES (KL) SDN BHD
#  MAKASSAR FRESH MARKET S/B
#  PINGHWAI TRADING SDN BHD
#  COSWAY (M) SDN BHD
#  HAI-O RAYA BHD
#  GREEN LANE PHARMACY SDN BHD
#  CHEF LEE SDN BHD
#  FOUR QUARTERS SDN BHD
#  ECOSWAY.COM SDN BHD
#  SIN THYE & COMPANY
#  NADEJE PLATINUM SDN BHD
#  ANEKA INTERTRADE MARKETING SDN BHD
#  BEST DENKI MALAYSIA
#  EDEN IMPRESSION SDN BHD
#  UROKO JAPANESE CUISINE SDN BHD
#  FTOF NOODLE HOUSE
#  EIGHT OUNCE COFFEE CO.
#  SKCA HARDWARE & TIMBER SDN. BHD.
#  ANN GIAP TRADING SDN BHD
#  KEDAI UHAT DAN RUNCIT CHONG HWA
#  K STATIONERY & OFFICE SUPPLIES
#  MPH BOOKSTORES SDN BHD
#  BECON STATIONER BECON ENTERPRISE SDN BHD
#  ECO-SHOP MARKETING SDN BHD
#  DE LUXE CIRCLE FRESH MART SDN BHD
#  VERBENA CONFECTIONERY SDN BHD
#  DOMINO'S PIZZA TAMAN UNIVERSITI
#  ENW HARDWARE CENTRE (M) SDN. BHD.
#  KFA SUPPLY
#  DIMILIKI OLEH T PLUS F&B SDN. BHD.
#  DIMILIKI OLEH: DOVE HOLDINGS SDN BHD
#  OLD TOWN KOPITIAM SDN BHD
#  THE MARCO POLO KITCH BUKIT INDAH
#  FARMASI LIGAMAS
#  SANYU STATIONERY SHOP
#  MYNEWS RETAIL SB
#  RAPID RAIL SDN BHD
#  ESJAY FUEL ENTERPRISE
#  MOONLIGHT CAKE HOUSE SDN BHD
#  LEMON TREE RESTAURANT JTJ FOODS SDN BHD
#  PASARAYA CINWA SDN BHD
#  KEDAI RUNCIT ZBH
#  GRANDMA HOMES RESTAURANT
#  IDEAL MENU GROUP SDN BHD
#  PASIR EMAS HARDWARE SDN BHD
#  RESTORAN DE COFFEE O
#  SANG KEE CHERAS RESTAURANT
#  10 GRAM GOURMET SBN BHD
#  LEONG HENG SHELL SERVICE STATION
#  PROSPER NIAGA
#  FILL IN ENTERPRISE
#  DION REALTIES SDN BHD
#  SANJUNG REALITI SDN. BHD.
#  OGN GROUP SDN BHD
#  PANDAH INDAH PULAU KETAM RESTAURANT
#  ONE ONE THREE SEAFOOD RESTAURANT SDN BHD
#  MEGAH RETAIL SDN BHD
#  GH DISTRIBUTOR & MARKETING SDN BHD
#  AMTECH ELECTRICAL SUPPLIES
#  KT WONG TRADING
#  OCEAN LC PACKAGING ENTERPRISE
#  PASAR RAYA MEGA MAJU (SEMENYIH) SDN BHD


# Sum keys roughly ordered by likelyhood.
sum_keys:
  - summe
  - summe eur
  - gesamtbetrag
  - gesantbetrag
  - gesamt
  - total
  - sum
  - zwischensumme
  - bar
  - te betalen
  - rockgeld
  - rusckgeld
  - rückgeld

ignore_keys:
  - mwst
  - kg x
  - stkx
  - stk
  - zw-summe

sum_format: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'

item_format: '([a-zA-Z].+)\s(-|)((\d|\d{2}),(\d{2}|\d{3}))\s'
item_format_metro: '[0-9]\s(.*?)\d.()((\d|\d{2})(\,|\.)\d{1,2})\s([A|a]|[B|b])'

# Matches dates like 19.08.15 and 19.08.2015
date_format: '((\d{2}\.\d{2}\.\d{2,4})|(\d{2,4}\/\d{2}\/\d{2})|(\d{2}\/\d{2}\/\d{4}))'
